spring:
  cloud:
    stream:
      function:
        definition: operat
      bindings:
        operat-in-0:
          destination: test2
          content-type: application/x-protobuf
        operat-out-0:
          destination: test1
          content-type: application/x-protobuf
      kafka:
        binder:
          brokers: localhost:9092