spring:
  cloud:
    stream:
      function:
        definition: produc
      bindings:
        produc-out-0:
          destination: test
      kafka:
        binder:
          brokers: 127.0.0.1:9092